name: prerelease

on:
  workflow_dispatch:
  push:
    tag:
      - "b*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set tag_name
        env:
          DATE: ${{ steps.date.outputs.date }}
        run: |
          echo "tag_name=b${{ github.ref_name }}_${DATE}" >> $GITHUB_ENV

      - name: Run build.sh
        run: sh build.sh ${{ env.tag_name }}

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ env.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag: Prerelease
          tag_name: ${{ env.tag_name }}
          files: tailscale_*.zip
          prerelease: true
          generate_release_notes: true
